Task formatting for invoices
invoiceninja/ui pull request #1038
Opened 2023-08-11 01:26 UTC by turbo124

2023-08-14 18:54 UTC, beganovich requested changes

2023-08-14 18:54 UTC, beganovich commented on src/pages/projects/common/hooks/useInvoiceProject.tsx
> +      tasks.forEach(async (task) => {
Why is this marked as `async`? I can't see `awaitable` impl?

2023-08-15 02:41 UTC, turbo124 commented
@beganovich updated.

2023-08-15 08:58 UTC, beganovich approved these changes
Looks good, thanks 👍️

2023-08-15 08:58 UTC, merged