[Cleanup] Invoice Edit Page CTAs
invoiceninja/ui pull request #1164
Opened 2023-10-04 16:15 UTC by Civolilah

In progress...

2023-10-06 22:23 UTC, turbo124 commented
@Civolilah this looks good. @beganovich what are your thoughts on making these secondary CTA's slighly smaller (height wise)

2023-10-09 09:50 UTC, beganovich requested changes

2023-10-09 09:50 UTC, beganovich commented on src/pages/invoices/edit/components/CommonActions.tsx
> +    <div className="flex space-x-3">
Make sure to use `<Inline>` here.

2023-10-09 09:51 UTC, beganovich commented
> @Civolilah this looks good. @beganovich what are your thoughts on making these secondary CTA's slighly smaller (height wise)

I think we should just stick to the default buttons, to keep it consistent.

2023-10-09 15:35 UTC, beganovich approved these changes

2023-10-09 15:35 UTC, merged