[Feature] Connect-Accounts
invoiceninja/ui pull request #263
Opened 2022-11-16 22:05 UTC by Civolilah

2022-11-17 13:00 UTC, beganovich requested changes
Looks good, minor changes needed.

2022-11-17 16:59 UTC, Civolilah commented on src/pages/settings/bank-accounts/index/BankAccounts.tsx
> +          'X-API-SECRET': 'password',
> 1. I am not sure we have X-Api-Secret?
> 2. We definitely don't wanna hardcode the secret, even if it exists.

Yeah, sure. I missed that. David sent me CURL and missed this part while copying. We don't need additional headers so I removed it.

2022-11-17 16:59 UTC, Civolilah commented on src/pages/settings/bank-accounts/index/BankAccounts.tsx
> +    window.open(`/yodlee/onboard/${tokenResponse?.data?.hash}`);
> For dealing with param replacements, make sure to use route helper.

changed

2022-11-18 13:06 UTC, beganovich approved these changes
Looks good, thanks :+1:

2022-11-18 13:07 UTC, merged