[FEATURE] Bank-transaction-import
invoiceninja/ui pull request #269
Opened 2022-11-19 11:56 UTC by Civolilah

Here is implemented solution for bank transaction import as all imports in react app.

Here are screenshots of how it looks:

![image](https://user-images.githubusercontent.com/51542191/202849580-6fb005f0-3a6c-4b9b-83cf-e75cca7b1727.png)

![image](https://user-images.githubusercontent.com/51542191/202849591-9d060e7e-fb34-45f9-bfab-691a91d95609.png)

2022-11-19 11:58 UTC, Civolilah commented
@turbo124 Please give me details how to complete the execution of this task as you mentioned on Jira's user story.

2022-11-22 12:39 UTC, turbo124 commented
@beganovich this looks good to me from function perspective :)

2022-11-22 16:00 UTC, beganovich requested changes
Looks great, just add a missing translation.

2022-11-22 16:00 UTC, beganovich commented on src/components/import/UploadImport.tsx
> +                  <span>Bank account</span>
Missing translation.

2022-11-22 17:33 UTC, Civolilah commented on src/components/import/UploadImport.tsx
> +                  <span>Bank account</span>
> Missing translation.

Great catch, fixed.

2022-11-23 13:06 UTC, beganovich commented
Looks good, thanks :+1:

2022-11-23 13:06 UTC, merged