[Feature] Disabling documents
invoiceninja/ui pull request #328
Opened 2022-12-24 15:49 UTC by Civolilah

Here are two screenshots of the document tab when the user does not have permission to upload them:

![Screenshot 2022-12-24 at 16 06 43](https://user-images.githubusercontent.com/51542191/209442828-3d15ca57-7b4b-4b60-a41d-86b4600cf8aa.png)

![Screenshot 2022-12-24 at 16 12 24](https://user-images.githubusercontent.com/51542191/209442831-0d973924-47a1-44c6-a4cd-74db888b6a38.png)

@turbo124 The uploading area is disabled when the user plan is different from `Enterprise' and this includes only `HOSTED' users. Apart from these two screenshots, this warning message will be placed on all routes where we have this kind of upload. The upgrade plan link is set to `user.company_user.ninja_portal_url`. I decided to post this text as an example message, we don't have any specific keyword for this purpose, but I changed it to `documents_upgrade_plan` after taking the screenshot, let me know if you agree with the suggested keyword for translation files. Let me know your thoughts.

2022-12-26 23:31 UTC, turbo124 commented
@Civolilah @beganovich LGTM!

2023-01-02 10:17 UTC, beganovich requested changes
Looks good, small changes needed.

2023-01-02 21:00 UTC, Civolilah commented on src/pages/settings/company/documents/components/Upload.tsx
> +      {showPlanAlert && planWarning}
sure, it is changed

2023-01-03 12:44 UTC, beganovich commented
Looks good, thanks 👍

2023-01-03 12:45 UTC, merged