Overview
invoiceninja/ui pull request #4
Opened 2022-01-25 20:07 UTC by THEO-184

pulling request from my overview branch.

2022-01-26 09:23 UTC, beganovich commented
Please remove the draft status of the PR when it is ready for review.

2022-01-26 09:51 UTC, THEO-184 commented
> Please remove the draft status of the PR when it is ready for review.

Please I don't get what you  mean by this. I don't know why it is been tagged as Draft.

2022-01-26 10:33 UTC, beganovich commented
I made it a draft because it's not ready for review.

2022-01-31 12:03 UTC, beganovich requested changes

2022-01-31 12:03 UTC, beganovich commented on src/pages/products/View.tsx
> +    );
This is not convenient with the rest of the application.

https://github.com/invoiceninja/ui/blob/main/src/pages/clients/show/components/Contacts.tsx

2022-01-31 12:03 UTC, beganovich commented on src/pages/products/View.tsx
> +    <Default>
Breadcrumbs can be passed into the component.
https://github.com/invoiceninja/ui/blob/main/src/pages/clients/show/Client.tsx#L83

2022-01-31 12:03 UTC, beganovich commented on src/pages/products/View.tsx
> +  const [ProductDetails, setProductDetails] = useState<ProductDetails>(
This variable is out of the convention of the project. Please use camelCase for variables.

2022-01-31 12:03 UTC, beganovich commented on src/pages/products/View.tsx
> +          <Element leftSide={t('Description')}>Product Description</Element>
This has no purpose. The product description should be pulled from the resource itself, not hardcoded.

2022-01-31 12:04 UTC, beganovich commented
Looks good, slight changes are needed.

There's a problem with how you handle tabs, we don't want duplicated page for this, rather re-rendering outlet, instead of a whole new page. An example of this is available on the client show page.

2022-02-01 09:42 UTC, merged