Permissions
invoiceninja/ui pull request #413
Opened 2023-01-21 15:20 UTC by beganovich

This implements a few missing permission checks for the app.

2023-01-21 15:48 UTC, beganovich commented on src/components/CompanySwitcher.tsx
> +    (isSelfHosted() || (isHosted() && !freePlan())) && companyUser?.is_admin; // @Todo: Needs confirmation.
@turbo124 for confirmation.

2023-01-21 15:48 UTC, beganovich commented on src/pages/dashboard/components/Totals.tsx
> +      // @Todo: Correct permission for fetching totals.
@turbo124 for confirmation.

2023-01-21 15:48 UTC, beganovich commented on src/pages/dashboard/components/Totals.tsx
> +      // @Todo: Correct permission for fetching totals.
@turbo124 for confirmation.

2023-01-21 15:48 UTC, beganovich commented on src/pages/purchase-orders/routes.tsx
> +          guards={[() => permission('view_purchase_order')]} // @Todo: Missing bitmask guard
@turbo124 for bitmask int.

2023-01-21 15:49 UTC, beganovich reviewed
Few things required before merge.

2023-01-21 21:43 UTC, turbo124 commented
public const MODULE_PURCHASE_ORDERS = 16384;

2023-01-21 21:44 UTC, turbo124 commented on src/components/CompanySwitcher.tsx
> +    (isSelfHosted() || (isHosted() && !freePlan())) && companyUser?.is_admin; // @Todo: Needs confirmation.
company_user.is_owner == true

only

2023-01-21 21:45 UTC, turbo124 commented on src/pages/dashboard/components/Totals.tsx
> +      // @Todo: Correct permission for fetching totals.
is_admin || is_owner

2023-01-21 21:45 UTC, turbo124 commented on src/pages/dashboard/components/Totals.tsx
> +      // @Todo: Correct permission for fetching totals.
is_admin || is_owner

2023-01-22 20:32 UTC, turbo124 commented on src/common/hooks/permissions/useHasPermission.ts
>    | 'edit_transaction';
please prefix with bank_transaction instead of transaction

2023-01-22 20:37 UTC, turbo124 requested changes
as a user not with transaction permissions, i am still seeing the transactions tab?

also, the transactions and recurring expenses are not appearing in the permissions list for me.

2023-01-31 14:45 UTC, beganovich commented
@turbo124 for revivew.

2023-02-03 01:40 UTC, turbo124 commented
@beganovich testing on this now looks good!

2023-02-14 16:04 UTC, beganovich commented
Closing in favor of #464 .

2023-02-14 16:04 UTC, closed without merging