Fixes for queries
invoiceninja/ui pull request #833
Opened 2023-06-25 07:07 UTC by turbo124

set draft balances to amount - fixes for queries when creating payments.

2023-06-25 15:03 UTC, beganovich commented
I'd assume this is QA passed?

2023-06-25 21:42 UTC, turbo124 commented
thanks!

2023-06-26 10:47 UTC, beganovich requested changes
Looks good, a tiny change needed :+1:

2023-06-26 10:47 UTC, beganovich commented on src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
> +          {invoiceSum.invoice.status_id === '1' ? formatMoney(invoiceSum.invoice.amount) :formatMoney(invoiceSum.invoice.balance)}
Needs fix: Use the status enum.

2023-06-26 15:03 UTC, merged